  # remove old POTFILES.in
  rm po/POTFILES
  # add warning
  echo "# DO NOT EDIT MANUALLY" >> po/POTFILES
  echo "# This files is autogenerated a by script." >> po/POTFILES
  # add metadata files
  echo "# METADATA files" >> po/POTFILES
  echo "data/nl.emphisia.icon.desktop.in.in" >> po/POTFILES
  echo "data/nl.emphisia.icon.metainfo.xml.in.in" >> po/POTFILES
  # add ui files
  echo "# UI files" >> po/POTFILES
  find src -name "*.blp*" -print | sort >> po/POTFILES
  # add rust files
  echo "# RUST files" >> po/POTFILES
  grep gettext src/ -r | grep .rs  | cut -d: -f1 | uniq | sort >> po/POTFILES